# Generated by Django 4.1.5 on 2023-01-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityMap',
            fields=[
                ('cityId', models.IntegerField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMap',
            fields=[
                ('districtId', models.IntegerField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('longDescription', models.TextField(default='')),
                ('price', models.FloatField(default=0)),
                ('constructionYear', models.IntegerField(default=0)),
                ('walkScore', models.IntegerField(default=0)),
                ('noRooms', models.IntegerField(default=0)),
                ('noBathrooms', models.IntegerField(default=0)),
                ('noBedrooms', models.IntegerField(default=0)),
                ('noFireplaces', models.IntegerField(default=0)),
                ('noGarages', models.IntegerField(default=0)),
                ('noParkingLots', models.IntegerField(default=0)),
                ('noPools', models.IntegerField(default=0)),
                ('photoUrl', models.CharField(max_length=255)),
                ('isNew', models.BooleanField(default=True)),
                ('googleMapAddressLink', models.CharField(max_length=255)),
                ('walkScoreMapped', models.CharField(max_length=255)),
                ('livingArea', models.FloatField(default=0)),
                ('contactEmail', models.CharField(max_length=255)),
                ('contactPhoneNumber', models.CharField(max_length=255)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrealestate_app.citymap')),
                ('districtId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montrealestate_app.districtmap')),
            ],
        ),
    ]
