# Generated by Django 4.1.5 on 2023-01-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrealestate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='constructionYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='livingArea',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longDescription',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noBathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noBedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noFireplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noGarages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noParkingLots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noPools',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='noRooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='walkScore',
            field=models.IntegerField(default=0),
        ),
    ]
