# Generated by Django 4.1.5 on 2023-01-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrealestate_app', '0003_remove_apartment_phototext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
