# Generated by Django 4.1.5 on 2023-01-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('montrealestate_app', '0005_remove_apartment_latitude_remove_apartment_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='category',
        ),
    ]
