# Generated by Django 4.1.5 on 2023-01-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrealestate_app', '0007_remove_apartment_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='googleMapAddressLink',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photoUrl',
            field=models.URLField(max_length=255),
        ),
    ]
