# Generated by Django 4.1.5 on 2023-01-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montrealestate_app', '0008_alter_apartment_googlemapaddresslink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='googleMapAddressLink',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photoUrl',
            field=models.CharField(max_length=255),
        ),
    ]
